"""empty message

Revision ID: 9901d38cd5a1
Revises: b456de1be258
Create Date: 2019-05-22 02:51:29.457552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9901d38cd5a1'
down_revision = 'b456de1be258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guests', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_column('guests', 'event_id')
    # ### end Alembic commands ###
