"""empty message

Revision ID: b456de1be258
Revises: 13c6ae448373
Create Date: 2019-05-22 02:50:11.298695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b456de1be258'
down_revision = '13c6ae448373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('guests_user_id_fkey', 'guests', type_='foreignkey')
    op.drop_column('guests', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('guests_user_id_fkey', 'guests', 'users', ['user_id'], ['id'])
    op.drop_table('events')
    # ### end Alembic commands ###
